//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
        }
    
        public int MaLop { get; set; }
        public string TenLop { get; set; }
        public Nullable<int> MaKhoi { get; set; }
        public Nullable<int> MaNgoaiNgu { get; set; }
        public Nullable<int> SiSo { get; set; }
    
        public virtual Khoi Khoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
        public virtual NgoaiNgu NgoaiNgu { get; set; }
    }
}
